### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by anushr** [thephpleague/omnipay-common#85]
@delatbabel / @kayladnls Not sure what your policy is on creating releases, but could you please make one for some of the recent commits?

A couple PRs I'm going to open for Stripe and AuthorizeNet depend on #83. I feel it's cleaner using a proper version in `composer.json` rather than resorting to `dev-master`.

**Comment by judgej** [comment]
Here are the current changes since the last release (v2.4.1):

https://github.com/thephpleague/omnipay-common/compare/v2.4.1...master

That's the master branch, which is still OmniPay 2.x AFAIK. Not looked at it in any detail yet, but it adds functionality so I would assume at least a minor version jump (to v2.5.0)

**Comment by delatbabel** [comment]
My normal policy on creating a release after merging PRs is to ask the PR author to verify that whatever he did works in production. I don't have keys for all gateways so I can't do that verification myself. In this case it's the common repo so perhaps it's time for a repo release.
